### ISSUE TITLE
[Billing UI] Values in tables may not refresh due to package bug

### ISSUE THREAD

**Issue by caravinci** [overture-stack/billing#108]
## Description
Due to the way `react-bootstrap-table` creates the keys for each cell, it may not update the values when switching between showing cost and usage. This seems to be an isolated issue when the value is 0, but may occur in other instances.
This issue may not come up in prod, as ideally, there won't be 0 usage/costs.

## Expected Behaviour
Cost and Usage values should be displayed accordingly, no matter the value.

## Actual Behaviour
When the value is 0, $0.00 is displayed after switching to usage.

## Possible Fixes
- not showing  $0.00 when no cost has been incurred
- replacing the package used for tables
- amending the issue in the package's codebase (the maintainers seem unresponsive)

**Comment by caravinci** [comment]
Think I may have found a workaround:
Currently, as a carryover from the previous implementation, I hide and show columns based on a boolean props `shouldShowCost`. If instead of having shown/hidden columns, we pass the props as state into the formatter, we may be able to update the format (which is in fact the issue here) on state changes.

Example for reference: https://react-bootstrap-table.github.io/react-bootstrap-table2/storybook/index.html?selectedKind=Work%20on%20Columns&selectedStory=Dummy%20Column&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel

**Comment by b-f-chan** [comment]
Tested on https://lab-billing.cancercollaboratory.org

- Cost values did not all change to zero when switching between Cost & Usage tabs when there is a 0 usage value
- Specifically, object usage was 0, hrs but when switching back to Cost tab, it correctly shows only the object cost as $0.00, the other cost values remain intact

Ready for PR review
