### ISSUE TITLE
[Billing UI] Stale/invalid session tokens are not being cleared

### ISSUE THREAD

**Issue by caravinci** [overture-stack/billing#109]
The app checks for existing session tokens in order to redirect the users either to content or back to login.
In the second case, when a token is deemed invalid, the app should clear the existing session token in order to avoid unnecessary conflicts.

Note: This issue is present in production

**Comment by b-f-chan** [comment]
Tested on lab-billing.cancercollaboratory.org

Able to now login properly, no token errors seen in console

Ready for PR review
