### ISSUE TITLE
[Billing UI] Summary data is not adding up correctly

### ISSUE THREAD

**Issue by caravinci** [overture-stack/billing#118]
The data displayed is not being summarised/added up correctly, in either the Summary table nor in the Details Table (once you apply grouping filters, e.g. Period, Project, User.)

**Comment by b-f-chan** [comment]
Tested on https://lab-billing.cancercollaboratory.org

Both summary table and details table totals now add up correctly when using the Group By function (Period, Project, User)

Ready for PR review
