### ISSUE TITLE
Do not charge for instances in 'SHELVED_OFFLOADED' state

### ISSUE THREAD

**Issue by jmimico** [overture-stack/billing#47]
Users have the ability to 'shelve' an instance, meaning the instance is powered off, snapshotted, and removed from the compute node releasing all cpu/memory/disk from the compute node so we should not be charging for instances in this state. This is a cost savings feature for users.

Looks like its a fairly simple change in https://github.com/CancerCollaboratory/billing/blob/develop/billing-api/billing_server/billing/usage_queries.py line 73.

**Comment by caravinci** [comment]
Seems the change mentioned was to add a 'shelved_offloaded' filter to vm_state in the query.
Deployed to lab for testing.
