### ISSUE TITLE
Fix security vulnerabilities in Billing

### ISSUE THREAD

**Issue by alekspejovic** [overture-stack/billing#50]
There is currently 51 alerts ranging in severity :

https://github.com/CancerCollaboratory/billing/network/alerts?page=1&q=is%3Aopen

Please make sure these are all addressed.

**Comment by b-f-chan** [comment]
23 alerts still present, need to verify these are handled after merge
https://github.com/overture-stack/billing/network/alerts

**Comment by b-f-chan** [comment]
Confirmed with @yuanhengzhao @caravinci that vulnerabilities in #57 are fixed here, closing #57

**Comment by b-f-chan** [comment]
Tested deployed version on prod, one issue found:

- By default, only 2 user records are being show on the billing tab.  There's 1178 records, so paging through by 2s is extremely painful.  Before, it used to show at least 20 records per page I believe, it seems some bug may have been introduced (unless I'm using it wrong but I don't think so).

![image.png](https://images.zenhubusercontent.com/5c8bff46913aca2929d7074d/59c4704f-025b-42dc-ac38-6e924b76d1dc)

**Comment by b-f-chan** [comment]
All of Henry's fixes are now reviewed, merged, and deployed to prod, closing
