### ISSUE TITLE
Add Object Storage Billing

### ISSUE THREAD

**Issue by b-f-chan** [overture-stack/billing#51]
We need to add this item to the customer reports, as well as their invoices.
In order for this to happen we must add an API query to the Collab Graphite database that stores this usage, as well as the corresponding handling in the app.

The information on how to access the database is available in this link to a [Wiki article on Object Storage usage tracking](https://wiki.oicr.on.ca/display/Collabor/Collaboratory+object+storage+usage+tracking) written by @jmimico.

**Comment by b-f-chan** [comment]
Tested on lab-billing.cancercollaboratory.org.  One critical issue found when running the billing script, and 3 minor issues in the UI.

**Billing Script**

The billing script fails at the e-mail step.  Normally, the output from the logs says the CSV is saved then sends the e-mails, like so:

`2020-02-19, 20:54:49 info: Email Mode. Generating Summary CSV file that will be emailed...
2020-02-19, 20:54:49 info: Saving file: /srv/files/January.csv
2020-02-19, 20:54:49 info: Emailing summary csv file...
2020-02-19, 20:54:49 info: Finished Processing Invoices.
2020-02-19, 20:54:49 info: /srv/files/January.csv saved`

But this is the error encountered:

`2020-03-12, 22:28:15 info: Email Mode. Generating Summary CSV file that will be emailed...
2020-03-12, 22:28:15 error: No invoices were actually generated?`

Looks like no invoices were actually generated, so the CSV file step fails perhaps because it can't find any data.  But the UI shows there is data, so not sure what’s going on.  I didn't execute any steps differently from last time.

**Comment by b-f-chan** [comment]
Script now works after undeleting the deleted Invoices in Freshbooks (known, existing issue, we have lived with this workaround for a while now, won't be fixing for this feature deployment).

For the actual Invoice, recommend we also fix the order to be consistent with what we have sent before, i.e., order of items should be: CPU, Image, Volume, Object

![image.png](https://images.zenhubusercontent.com/5c8bff46913aca2929d7074d/0d824619-e6f0-44f8-814a-68a2b8530a89)

**Comment by b-f-chan** [comment]
After discussing with @caravinci , the new order makes sense.  It is alphabetical in case we support other charge types in future and the list grows long.  Both the UI and Invoice are consistent in that order.

So we just need to fix the two other UI issues.

**Comment by caravinci** [comment]
Issues addressed. New image deployed and running in the lab environment.

**Comment by b-f-chan** [comment]
UI issues resolved:

-  If there is no Object Storage usage for the given period, it now shows $0.00 instead of blank in both the summary table and the results table
- Object Storage now shows in the results table at the project level only

Ready for PR review
