### ISSUE TITLE
Billing UI CSV Export Missing Columns

### ISSUE THREAD

**Issue by b-f-chan** [overture-stack/billing#70]
Billing UI CSV export missing these columns:

- Period
- Total

Note that the Period only shows up if the user clicks the 'Period' tab in the UI, but this doesn't make sense.  The Period should always be included.  Additionally, the Period shows up as 2 columns, 'fromDate' and 'toDate' (which is OK, this is just an FYI).

See attached example (CSV converted to XLSX) - UI has the columns, but file does not:

![image](https://user-images.githubusercontent.com/40768946/68901958-0d719580-0705-11ea-9232-1c1c20721cfe.png)

[billing-ui-sample-export.xlsx](https://github.com/overture-stack/billing/files/3848955/billing-ui-sample-export.xlsx)

Here is what the fromDate and toDate look like in the CSV if Period tab is clicked:

![image.png](https://images.zenhubusercontent.com/5c8bff46913aca2929d7074d/4167cb72-86bc-4908-a7fc-5d4b13ca0559)

**Comment by caravinci** [comment]
This issue seems to be removed as an added bonus from dealing with #90... "in progress" while validating.

**Comment by b-f-chan** [comment]
Tested on lab-billing.cancercollaboratory.org

Missing columns now present in CSV, ready for PR review
