### ISSUE TITLE
Give Billing UI CSV Export Proper Filename

### ISSUE THREAD

**Issue by b-f-chan** [overture-stack/billing#72]
Currently the billing UI's CSV export simply downloads as "spreadsheet.csv".

Rename it with a more intelligible default, for example:

- "collaboratory_usage_billing_export_periodStart_to_periodEnd"

Where:

- periodStart is the start of the period being exported from the UI, in yyyymmdd format
- periodEnd is the end of the period being exported from the UI, in yyyymmdd format

For example: "collaboratory_usage_billing_export_20191014_to_20191114"

Or something similarly useful.

**Comment by caravinci** [comment]
Went a bit beyond, naming the file according to the bucket selected for the report.

**Comment by b-f-chan** [comment]
Tested at https://lab-billing.cancercollaboratory.org/

Found a minor issue with the CSV export:

(1) For example, I choose a time period of Dec 1, 2020 to Jan 1, 2021.  I click Generate Report, results display in UI.   Then I click Export to CSV.  Filename is correctly suffixed with 20201201_to_20210101.  File contents also for correct time period.

(2) However, next I change the time period in the UI from Aug 1, 2020 to Jan 2, 2021, but DON’T click Generate Report.  I then click Export to CSV.  File contents are correct (they are still from Dec 1, 2020 to Jan 1, 2021), since I didn’t click Generate Report.  However, the filename is incorrectly suffixed with 20200801_to_20210101.

My guess is the app is just directly reading the latest values in the time period input boxes, without checking if that is the actual result displayed.  I’m not sure if adding that check is worth it for this minor issue, but the filename is incorrect if it should be based on the actual generated results.

**Comment by caravinci** [comment]
Issue addressed, testable in the lab.

**Comment by b-f-chan** [comment]
Re-tested at https://lab-billing.cancercollaboratory.org

Filename now correctly reflects the period of data that was actually generated in the table, and not just what values are currently in the input boxes (whether they click Generate or not).

Ready for PR review.
